version: '3.9'

name: innoclinic

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    expose:
      - "${MSSQL_PORT}:1433"
    environment:
      # Read from env at deploy time; never commit values in Git
      MSSQL_SA_PASSWORD: ${MSSQL_DB_PASSWORD}
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools18/bin/sqlcmd -S localhost -U ${MSSQL_DB_USER} -P ${MSSQL_DB_PASSWORD} -C || exit 1"]
      interval: 10s
      retries: 10
      start_period: 90s
      timeout: 10s

    # No volumes -> ephemeral DB for dev
    
  mongo-db:
    image: mongo:6.0
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    expose:
      - "${MONGODB_PORT}:27017"
    healthcheck:
      test: >
        echo "try { rs.status() } catch (err) {
          rs.initiate({_id:'rs0', members:[{_id:0, host:'mongo-db:${MONGODB_PORT}'}]})
        }" | mongosh --quiet --port ${MONGODB_PORT}
      interval: 5s
      timeout: 30s
      retries: 30
      start_period: 30s

  auth-api:
    image: ${IMAGE_REPOSITORY}:${IMAGE_AUTH_API}
    depends_on:
      mssql-db:
        condition: service_healthy
    expose:
      - "${AUTH_API_PORT}:10036"
    environment:
      # ASP.NET Core maps ConnectionStrings__DefaultConnection into Configuration.GetConnectionString("DefaultConnection")
      # "sa" is the default system administrator account
      # server name resolves from db service name above
      ASPNETCORE_URLS: http://+:${AUTH_API_PORT}
      ASPNETCORE_ENVIRONMENT: Development
      EmailSettings__SmtpPort: "${SMTP_PORT}"
      EmailSettings__SmtpHost: "${SMTP_HOST}"
      EmailSettings__From: "${SMTP_FROM}"
      EmailSettings__DisplayName: "${SMTP_DISPLAY_NAME}"
      EmailSettings__CredUserName: "${SMTP_USER_NAME}"
      EmailSettings__CredPassword: "${SMTP_PASSWORD}"
      ConnectionStrings__AuthorizationDb: "Server=mssql-db;Database=Authorization;User Id=${MSSQL_DB_USER};Password=${MSSQL_DB_PASSWORD};TrustServerCertificate=True;"
      AppUrls__ProfilesUrl: "http://profiles-api:${PROFILES_API_PORT}"
      AppUrls__OfficesUrl: "http://office-api:${OFFICES_API_PORT}"
      AppUrls__EmployeeUiUrl: "https://${EMPLOYEE_UI_DNS}"
      AppUrls__ClientUiUrl: "https://${CLIENT_UI_DNS}"
      AppUrls__AuthUrl: "https://${AUTH_API_DNS}"
      IdentityServerCreds__LicenseKey: "${ID_SERVER_LICENSE_KEY}"
      
  profiles-api:
    image: ${IMAGE_REPOSITORY}:${IMAGE_PROFILES_API}
    depends_on:
      mssql-db:
        condition: service_healthy
    expose:
      - "${PROFILES_API_PORT}:7036"
    environment:
      # ASP.NET Core maps ConnectionStrings__DefaultConnection into Configuration.GetConnectionString("DefaultConnection")
      # "sa" is the default system administrator account
      # server name resolves from db service name above
      ASPNETCORE_URLS: http://+:${PROFILES_API_PORT}
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ProfilesDb: "Server=mssql-db;Database=Profiles;User Id=${MSSQL_DB_USER};Password=${MSSQL_DB_PASSWORD};TrustServerCertificate=True;"
      ConnectionStrings__AuthUrl: "https://${AUTH_API_DNS}"
      
  documents-api:
    image: ${IMAGE_REPOSITORY}:${IMAGE_DOCS_API}
    depends_on:
      mssql-db:
        condition: service_healthy
    expose:
      - "${DOCS_API_PORT}:9096"
    environment:
      ASPNETCORE_URLS: http://+:${DOCS_API_PORT}
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DocumentsDb: "Server=mssql-db;Database=Documents;User Id=${MSSQL_DB_USER};Password=${MSSQL_DB_PASSWORD};TrustServerCertificate=True;"
      AwsSettings__Endpoint: "${S3_ENDPOINT}"
      AwsSettings__AccessKey: "${S3_ACCESS_KEY}"
      AwsSettings__SecretKey: "${S3_SECRET_KEY}"
      AwsSettings__BucketName: "${S3_BUCKET_NAME}"
      AwsSettings__PhotoDoctorPath: "${S3_PHOTO_DOCTORS_PATH}"
      AwsSettings__PhotoReceptionistPath: "${S3_PHOTO_RECEPTS_PATH}"
      AwsSettings__PhotoPatientPath: "${S3_PHOTO_PATIENTS_PATH}"
      AwsSettings__PhotoOfficePath: "${S3_PHOTO_OFFICES_PATH}"
      
  
  offices-api:
    image: ${IMAGE_REPOSITORY}:${IMAGE_OFFICES_API}
    depends_on:
      mongo-db:
        condition: service_healthy
    expose:
      - "${OFFICES_API_PORT}:8269"
    environment:
      ASPNETCORE_URLS: http://+:${OFFICES_API_PORT}
      ASPNETCORE_ENVIRONMENT: Development
      MongoDbSettings__MongoDbUri: "mongodb://mongo-db:${MONGODB_PORT}/innoclinic"
      MongoDbSettings__DatabaseName: "innoclinic"
      ConnectionStrings__AuthUrl: "https://${AUTH_API_DNS}"
      
  employee-ui:
    image: ${IMAGE_REPOSITORY}:${IMAGE_EMPLOYEE_UI}
    expose:
      - "${EMPLOYEE_UI_PORT}"
    environment:
      PROFILES_API_URL: "https://${PROFILES_API_DNS}"
      OFFICES_API_URL: "https://${OFFICES_API_DNS}"
      AUTH_API_URL: "https://${AUTH_API_DNS}"
      DOCS_API_URL: "https://${DOCS_API_DNS}"
      EMPLOYEE_UI_URL: "https://${EMPLOYEE_UI_DNS}"
    depends_on:
      - auth-api
      - profiles-api
      - offices-api
      - documents-api

  client-ui:
    image: ${IMAGE_REPOSITORY}:${IMAGE_CLIENT_UI}
    expose:
      - "${CLIENT_UI_PORT}"
    environment:
      PROFILES_API_URL: "https://${PROFILES_API_DNS}"
      OFFICES_API_URL: "https://${OFFICES_API_DNS}"
      AUTH_API_URL: "https://${AUTH_API_DNS}"
      DOCS_API_URL: "https://${DOCS_API_DNS}"
    depends_on:
      - auth-api
      - profiles-api
      - offices-api
      - documents-api